feat: add support for bitstring statuslist
SAP/ssi-dim-middle-layer pull request #125
Opened 2024-11-11 15:59 UTC by Phil91

Refs: #80

## Description

* add support for bitstring statuslists while creating the issuer wallet
* add support to create a bitstring statuslist via api 

## Why

To don't have the need to use the deprecated StatusList2021

## Issue

#80 

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added copyright and license headers, footers (for .md files) or files (for images)

2025-02-05 13:42 UTC, evegufy requested changes

2025-02-05 13:42 UTC, evegufy commented on charts/dim/values.yaml
> +    statusListType: "BitstringStatusList"
please change default value to StatusList2021, as the overall change to BitstringStatusList has been postponed.

2025-02-05 13:45 UTC, Phil91 commented on charts/dim/values.yaml
> +    statusListType: "BitstringStatusList"
adjusted

2025-02-07 11:21 UTC, evegufy approved these changes

2025-02-07 11:42 UTC, merged