fix(callback): add error handling for callback service
SAP/ssi-dim-middle-layer pull request #73
Opened 2024-07-31 14:07 UTC by Phil91

## Description

add error handling to the callback service

## Why

Currently the callback is send without a check if the call was successful, this results in the process step always succeeding even if the callback call failed.

## Issue

Refs: #67

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added copyright and license headers, footers (for .md files) or files (for images)

2024-08-01 14:19 UTC, evegufy requested changes

2024-08-01 14:19 UTC, evegufy commented on tests/processes/DimProcess.Library.Tests/CallbackServiceTests.cs
> + * Copyright 2024 SAP SE or an SAP affiliate company and ssi-dim-middle-layer contributors.
Please add BMW for all new files

2024-08-02 06:21 UTC, Phil91 commented on tests/processes/DimProcess.Library.Tests/CallbackServiceTests.cs
> + * Copyright 2024 SAP SE or an SAP affiliate company and ssi-dim-middle-layer contributors.
Added

2024-08-02 13:59 UTC, evegufy approved these changes

2024-08-02 14:35 UTC, merged